name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install ruff codespell

      - name: Codespell
        run: codespell .

      - name: Ruff check
        run: ruff check src/ tests/

      - name: Ruff format
        run: ruff format --check --diff src/ tests/

  static:
    name: Static type check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pyright 'ops[testing]' -r requirements.txt

      - name: Pyright
        run: pyright
        env:
          PYTHONPATH: lib:src
