name: Janitor

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@main
    with:
      dry_run: ${{ github.event.inputs.dry_run || 'false' }}
      keep_workflows: "pipeline.yaml,pre-commit.yaml"
