name: Janitor

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@bb58903c9ab6fed38da23a5b35a3cf294e82d4a4
    with:
      dry_run: ${{ inputs.dry_run }}
      keep_workflows: "pipeline.yaml,prek.yaml"
