name: Refresh Charm Cache

on:
  schedule:
    - cron: '0 0 */6 * *' # Every ~6 days at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  refresh:
    uses: canonical/launchpad-actions/.github/workflows/refresh-charm-cache.yaml@bb58903c9ab6fed38da23a5b35a3cf294e82d4a4
    with:
      charm_path: "."
