name: Refresh Charm Cache

on:
  schedule:
    - cron: '0 0 */6 * *' # Every ~6 days at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  refresh:
    uses: canonical/launchpad-actions/.github/workflows/refresh-charm-cache.yaml@69c806b0960935a6307170f6621a72e7d4720581
    with:
      charm_path: "."
