name: Refresh Charm Cache

on:
  schedule:
    - cron: '0 0 */6 * *' # Every ~6 days at 00:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  refresh:
    uses: canonical/launchpad-actions/.github/workflows/refresh-charm-cache.yaml@22042cbf700109723b206042f77bdcf134a26a52
    with:
      charm_path: "."
